services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
      - MONGO_URI=mongodb+srv://bcc1nc1oglu:0KOB9YyptmEPjSAL@cluster0.9djsobr.mongodb.net/leaderboard
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # Redis verileri için kalıcı hacim
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data:
